amazon:
  defaultRegion: us-east-2
  dynamodb:
    endpoint: http://localhost:8000

featureToggle:
  useLocalEndpoint: false

mqtt:
  host-url: tcp://test.mosquitto.org:1883
  default-topic: techlab_sapphire_cd_2020
  clientID: techlab-sapphire